'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''HTMLEditor class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class HTMLEditor

    '''<summary>
    '''txtText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdBold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdBold As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdItalic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdItalic As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdUnderline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdUnderline As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdCenter As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdRule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdRule As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdLineBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdLineBreak As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtInput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInput As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdLink As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdImage As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''cmdFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdFile As Global.System.Web.UI.WebControls.Button
End Class
